#Rusheel Sharma
#I069
#BTech AI Sem V
#DL Lab 1

In [ ]:
import numpy as np
import tensorflow as tf

#Task 1

Exploring Tensorflow playground
1.	Open Tensorflow playground.
2.	Know the different features.
3.	Use different number, types of inputs and observe the output.
4.	Summarize your observations and inferences.


In [ ]:
tf.__version__

'2.18.0'

In [ ]:
x = tf.constant([])

In [ ]:
#scalar
sc = tf.constant(7)
print(sc)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
#vector
vc = tf.constant([10,10])
vc2 = tf.constant([[10],[10]])
print(vc,vc2)

tf.Tensor([10 10], shape=(2,), dtype=int32) tf.Tensor(
[[10]
 [10]], shape=(2, 1), dtype=int32)


In [ ]:
#matrix
M = tf.constant([[10,7],[7,10]])
print(M)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


In [ ]:
#multi-dim
tensor = tf.constant([[[1,2,3],[4,5,6]]])
print(tensor)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)


#Task2

Perform basic operations using Tensorflow (Defining constants, variables, concatenation, add, multiply, reduce mean, reduce sum)

In [ ]:
var = tf.Variable([10,7])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
var.assign([4,5])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 5], dtype=int32)>

In [ ]:
var.assign_add([1,1])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 6], dtype=int32)>

In [ ]:
var.assign_sub([2,2])
var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 4], dtype=int32)>

In [ ]:
mul = tf.multiply(M,M)
mul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 49, 100]], dtype=int32)>

In [ ]:
div = tf.divide(mul,M)
div

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.,  7.],
       [ 7., 10.]])>

In [ ]:
rm = tf.random.uniform(shape=[5,300])
rm2 = tf.random.uniform(shape=[5,300])
rs = tf.matmul(rm,tf.transpose(rm2))
rs

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[71.192795, 75.19972 , 77.30524 , 80.646545, 74.79071 ],
       [74.69861 , 78.352486, 81.21193 , 80.53564 , 77.68584 ],
       [77.90871 , 77.10823 , 82.28703 , 80.86358 , 81.07969 ],
       [72.71721 , 74.27354 , 75.84098 , 77.33832 , 74.62357 ],
       [68.61351 , 73.74401 , 71.30977 , 77.72151 , 75.8367  ]],
      dtype=float32)>

In [ ]:
con = tf.concat([rm,rm2],axis=0)
con

<tf.Tensor: shape=(10, 300), dtype=float32, numpy=
array([[0.72857416, 0.4461894 , 0.49126387, ..., 0.37024713, 0.4835626 ,
        0.40439117],
       [0.5111356 , 0.43037164, 0.34401608, ..., 0.40824127, 0.09408927,
        0.06421041],
       [0.92444897, 0.03412271, 0.2410003 , ..., 0.84939945, 0.3068099 ,
        0.69564056],
       ...,
       [0.10027921, 0.21737218, 0.08808911, ..., 0.20475376, 0.8809658 ,
        0.5431243 ],
       [0.30970836, 0.67150295, 0.56579375, ..., 0.68288064, 0.83088446,
        0.01520967],
       [0.8563987 , 0.01707304, 0.20151365, ..., 0.8749007 , 0.50946736,
        0.76626766]], dtype=float32)>

In [ ]:
tp = tf.multiply(vc,5)
tp

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([50, 50], dtype=int32)>

In [ ]:
reducem = tf.reduce_max(M)
reducem

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
reduces = tf.reduce_min(M)
reduces

<tf.Tensor: shape=(), dtype=int32, numpy=7>

#Task3

Perform linear algebra operations using Tensorflow (transpose, matrix multiplication, elementwise multiplication, determinant)

In [ ]:
matrix1 = tf.constant([[1, 2], [3, 4]])
matrix2 = tf.constant([[5, 6], [7, 8]])

transpose = tf.transpose(matrix1)

matmul = tf.matmul(matrix1, matrix2)

In [ ]:
transpose

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [ ]:
matmul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [ ]:
elemul = tf.multiply(matrix1, matrix2)
elemul

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]], dtype=int32)>

In [ ]:
d = tf.cast(matrix1, dtype=tf.float32)
d

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
det = tf.linalg.det(d)
det

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

#Task4

Perform derivative and higher order derivative for function f(x) = x^3 using gradient tape of Tensorflow

In [ ]:
import tensorflow as tf

x = tf.constant(5.0)

with tf.GradientTape() as t1:
    t1.watch(x)

    with tf.GradientTape() as t2:
        t2.watch(x)
        y = x **3

    dy_dx = t2.gradient(y, x)

d2y_dx2 = t1.gradient(dy_dx, x)

print("First-order derivative (dy_dx)", dy_dx)
print("Second-order derivative (d2y_dx2)", d2y_dx2)

First-order derivative (dy_dx) tf.Tensor(75.0, shape=(), dtype=float32)
Second-order derivative (d2y_dx2) tf.Tensor(30.0, shape=(), dtype=float32)


In [ ]:
print(dy_dx.numpy())

75.0


#Task5

Compute WX+b using Tensorflow where W, X,  and b are drawn from a random normal distribution. W is of shape (4, 3), X is (3,1) and b is (4,1)

In [ ]:
x = tf.constant(np.random.randn(3,1))
w = tf.constant(np.random.randn(4,3))
b = tf.constant(np.random.randn(4,1))
y = tf.add(tf.matmul(w,x),b)
y

<tf.Tensor: shape=(4, 1), dtype=float64, numpy=
array([[ 3.71689274],
       [-0.04429285],
       [-3.08236801],
       [-6.95277363]])>

#Task6

Compute Gradient of sigmoid function using Tensor flow

In [ ]:
x = tf.constant(5.0)

with tf.GradientTape() as tape:

    tape.watch(x)

    y = tf.sigmoid(x)

gradient = tape.gradient(y, x)

print(f"Input x: {x.numpy()}")
print(f"Sigmoid of x: {y.numpy()}")
print(f"Gradient of sigmoid at x: {gradient.numpy()}")

Input x: 5.0
Sigmoid of x: 0.9933071732521057
Gradient of sigmoid at x: 0.0066480329260230064


Conclusion : Gained hands-on experience with the TensorFlow library by executing a range of basic functions and operations.